
library(CytoTRACE)
library(Seurat)
setwd("/share/home/luhuan/AMLsc/cytoTRACE")

humandata<-readRDS("Rdata_forDEG.rds.gz")
phenotype<-read.table("phenotype",head=F,sep="\t")
a<-phenotype$V2
names(a)<-phenotype$V1
k=subset(humandata,subset=(sam =="P10a"))
P10a<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P10b"))
P10b<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P1a"))
P1a<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P1b"))
P1b<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P2a"))
P2a<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P2b"))
P2b<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P3a"))
P3a<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P3b"))
P3b<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P4a"))
P4a<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P4b"))
P4b<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P5a"))
P5a<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P5b"))
P5b<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P6a"))
P6a<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P6b"))
P6b<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P7a"))
P7a<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P7b"))
P7b<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P8a"))
P8a<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P8b"))
P8b<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P9a"))
P9a<-as.matrix(GetAssayData(k, slot = "counts"))
k=subset(humandata,subset=(sam =="P9b"))
P9b<-as.matrix(GetAssayData(k, slot = "counts"))
library(reticulate)

datasets <- list(P1a,P1b,P2a,P2b,P3a,P3b,P4a,P4b,P5a,P5b,P6a,P6b,P7a,P7b,P8a,P8b,P9a,P9b,P10a,P10b)

results <- iCytoTRACE(datasets,ncores = 30,enableFast = FALSE)
save.image("/data/AMLscRNA/mergeblood/20220501/cytotrace/cytotrace.Rdata")
saveRDS(results, file = "result.rds")
write.table(results$CytoTRACE,"results.bed",sep="\t",quote=F)
write.table(results$CytoTRACErank,"CytoTRACErank",sep="\t",quote=F)
write.table(results$GCS,"GCS",sep="\t",quote=F)
write.table(results$cytoGenes,"cytoGenes",sep="\t",quote=F)
